### ISSUE TITLE
[Error] Failed to load FXML

### ISSUE THREAD

**Issue by dolphin2410** [dolphin2410/McSR#3]
StackTrace

```
Caused by: java.lang.NullPointerException: inputStream is null.
        at javafx.fxml/javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2562)
        at javafx.fxml/javafx.fxml.FXMLLoader.load(FXMLLoader.java:2532)
        at mcsr/io.github.dolphin2410.mcsr.gui.SceneManager.<clinit>(SceneManager.kt:15)

```

`resources` 안에 폴더 정리후 발생

**Comment by dolphin2410** [comment]
Fixed [#511b472](https://github.com/dolphin2410/mcsr/commit/511b472)
